### ISSUE TITLE
fix the (recently) introduced HTTP 500 error

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#415]
While downloading a dump, a lot of errors arise, probably all due to the recently introduced 'role'functionality:

```python
2023-08-21 10:08:26,666|ERROR|11601|StorageLODHandler|get_storage_record|62|Exception
Traceback (most recent call last):
  File "/home/wmelder/git/beng-lod-server/src/apis/resource/StorageLODHandler.py", line 42, in get_storage_record
    data = self._storage_2_lod(url, return_format)
  File "/home/wmelder/git/beng-lod-server/src/apis/resource/StorageLODHandler.py", line 116, in _storage_2_lod
    result_object = self._transform_json_to_rdf(json_data)
  File "/home/wmelder/git/beng-lod-server/src/apis/resource/SDOStorageLODHandler.py", line 40, in _transform_json_to_rdf
    return SDORdfConcept(json_obj, cat_type, self.profile, self.cache)
  File "/home/wmelder/git/beng-lod-server/src/models/SDORdfConcept.py", line 79, in __init__
    self.__payload_to_rdf(metadata["payload"], self.itemNode, self.classUri)
  File "/home/wmelder/git/beng-lod-server/src/models/SDORdfConcept.py", line 720, in __payload_to_rdf
    role = SDORdfConcept._get_role(used_path, payload, new_payload_item)
  File "/home/wmelder/git/beng-lod-server/src/models/SDORdfConcept.py", line 508, in _get_role
    concept[name_metadata_field][path_parts[-1].strip()] == subject_name
KeyError: 'resolved_value'
2023-08-21 10:08:26,667|ERROR|11601|resource_api|_get_lod_resource|178|HTTP error 500 in response from the flex data store.
127.0.0.1 - - [21/Aug/2023 10:08:26] "GET /id/program/2101608050036042431 HTTP/1.1" 500 -
2023-08-21 10:08:26,667|INFO|11601|_internal|_log|186|127.0.0.1 - - [21/Aug/2023 10:08:26] "GET /id/program/2101608050036042431 HTTP/1.1" 500 -
```

- [x] Analyse this 
- [ ] Fix this

**Comment by wmelder** [comment]
Error occurs when the flex store metadata returns the following content for `crew.name`: 
`{'value': '1320590', 'origin': 'https://studio.mam.beeldengeluid.nl/api/metadata/thesaurus/~THE22/1320590'}`

**Comment by wmelder** [comment]
another error, slightly different cause:
```python
2023-08-22 14:19:35,757|ERROR|3648|StorageLODHandler|get_storage_record|62|Exception
Traceback (most recent call last):
  File "/home/wmelder/git/beng-lod-server/src/apis/resource/StorageLODHandler.py", line 42, in get_storage_record
    data = self._storage_2_lod(url, return_format)
  File "/home/wmelder/git/beng-lod-server/src/apis/resource/StorageLODHandler.py", line 116, in _storage_2_lod
    result_object = self._transform_json_to_rdf(json_data)
  File "/home/wmelder/git/beng-lod-server/src/apis/resource/SDOStorageLODHandler.py", line 40, in _transform_json_to_rdf
    return SDORdfConcept(json_obj, cat_type, self.profile, self.cache)
  File "/home/wmelder/git/beng-lod-server/src/models/SDORdfConcept.py", line 77, in __init__
    self.__payload_to_rdf(metadata["payload"], self.itemNode, self.classUri)
  File "/home/wmelder/git/beng-lod-server/src/models/SDORdfConcept.py", line 703, in __payload_to_rdf
    role = SDORdfConcept._get_role(used_path, payload, new_payload_item)
  File "/home/wmelder/git/beng-lod-server/src/models/SDORdfConcept.py", line 506, in _get_role
    name_value_field in concept[name_metadata_field]
KeyError: 'crew.name'
2023-08-22 14:19:35,759|ERROR|3648|resource_api|_get_lod_resource|178|HTTP error 500 in response from the flex data store.
127.0.0.1 - - [22/Aug/2023 14:19:35] "GET /id/series/2101608030022634031 HTTP/1.1" 500 -
```

**Comment by wmelder** [comment]
Apparently, some crew data doesn't have a 'crew.name', but it does have a 'crew.role' (see extra debug logging)
```python
2023-08-22 14:45:10,034|DEBUG|8508|SDORdfConcept|_get_role|507|
{'crew.role': {'value': '1892872', 'origin': 'https://studio.mam.beeldengeluid.nl/api/metadata/dictionary/~DIC16/1892872', 'resolved_value': 'art-director'}}
2023-08-22 14:45:10,034|ERROR|8508|SDORdfConcept|_get_role|518|Error in get_role.
Traceback (most recent call last):
  File "/home/wmelder/git/beng-lod-server/src/models/SDORdfConcept.py", line 509, in _get_role
    name_value_field in concept[name_metadata_field]
KeyError: 'crew.name'
```
